import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f4f5f4',
    },
    header: {
        backgroundColor: '#042d1f',
        width: '100%',
        paddingBottom: 25,
        alignItems: 'center',
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        zIndex: 10,
        position: 'relative',
    },
    backButton: {
        position: 'absolute',
        left: 20,
        padding: 5,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 22,
        fontFamily: 'InterDisplay-SemiBold',
        fontWeight: 'bold',
        marginTop: 20,
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 40,
    },
    centerBox: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    badgeCard: {
        width: (width - 60) / 2, // 2 columns layout
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 15,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    badgeImageWrapper: {
        position: 'relative',
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: '#EAEAEA',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#042d1f',
        marginBottom: 12,
    },
    lockOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1A1A1A',
        textAlign: 'center',
        fontFamily: 'InterDisplay-SemiBold',
        marginBottom: 4,
    },
    badgeDesc: {
        fontSize: 11,
        color: '#666',
        textAlign: 'center',
        fontFamily: 'Inter',
    },
    insigniaModalContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 30,
    },
    insigniaCloseButton: {
        position: 'absolute',
        top: 40,
        left: 20,
        padding: 10,
        zIndex: 20,
    },
    insigniaModalImageWrapper: {
        width: 250,
        height: 250,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
    },
    insigniaDatePill: {
        backgroundColor: '#042d1f',
        borderRadius: 12,
        paddingHorizontal: 25,
        paddingVertical: 10,
        marginBottom: 35,
        alignItems: 'center',
    },
    insigniaDateText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'InterDisplay-SemiBold',
    },
    insigniaDescriptionText: {
        fontSize: 18,
        color: '#1A1A1A',
        textAlign: 'center',
        lineHeight: 26,
        fontFamily: 'InterDisplay-Regular',
    },
    insigniaBoldText: {
        fontWeight: 'bold',
        fontFamily: 'InterDisplay-SemiBold',
    },
});
