import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f4f5f4',
    },
    header: {
        backgroundColor: '#042d1f',
        width: '100%',
        paddingBottom: 30,
        alignItems: 'center',
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        zIndex: 10,
        position: 'relative',
    },
    settingsButton: {
        position: 'absolute',
        top: 20,
        right: 20,
        padding: 5,
    },
    profileImageContainer: {
        marginTop: 40,
        position: 'relative',
        marginBottom: 15,
    },
    profileImagePlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#F5E8C7',
        justifyContent: 'center',
        alignItems: 'center',
    },
    editIconContainer: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: '#A3C68C',
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#042d1f',
    },
    userName: {
        color: '#fff',
        fontSize: 22,
        fontFamily: 'InterDisplay-SemiBold',
        fontWeight: 'bold',
        marginBottom: 5,
    },
    userEmail: {
        color: '#fff',
        fontSize: 12,
        opacity: 0.9,
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 100, // For the bottom nav bar spacing
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1A1A1A',
        fontFamily: 'InterDisplay-SemiBold',
    },
    historyCard: {
        backgroundColor: '#f4f5f4',
        borderWidth: 1,
        borderColor: '#dcdcdc',
        borderRadius: 8,
        padding: 15,
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    historyRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    historyText: {
        fontSize: 12,
        color: '#1A1A1A',
        fontWeight: '500',
    },
    historyDivider: {
        height: 1,
        backgroundColor: '#e0e0e0',
        marginBottom: 15,
    },
    achievementsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
    },
    achievementBadge: {
        width: (width - 70) / 4,
        alignItems: 'center',
        marginBottom: 15,
    },
    badgeImageWrapper: {
        position: 'relative',
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: '#EAEAEA',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#042d1f',
    },
    achievementLockedImage: {
        opacity: 0.35,
    },
    lockOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    achievementText: {
        marginTop: 6,
        fontSize: 10,
        fontWeight: 'bold',
        color: '#1A1A1A',
        textAlign: 'center',
        fontFamily: 'InterDisplay-SemiBold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: width - 40,
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#042d1f',
        fontFamily: 'InterDisplay-SemiBold',
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 6,
        fontFamily: 'InterDisplay-SemiBold',
    },
    textInput: {
        backgroundColor: '#f9f9f9',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 10,
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 15,
        color: '#333',
        marginBottom: 15,
    },
    modalButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: '#e0e0e0',
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        marginRight: 10,
    },
    cancelButtonText: {
        color: '#333',
        fontSize: 16,
        fontWeight: 'bold',
    },
    saveButton: {
        flex: 1,
        backgroundColor: '#042d1f',
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        marginLeft: 10,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    insigniaModalContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 30,
    },
    insigniaCloseButton: {
        position: 'absolute',
        top: 40,
        left: 20,
        padding: 10,
        zIndex: 20,
    },
    insigniaModalImageWrapper: {
        width: 250,
        height: 250,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
    },
    insigniaDatePill: {
        backgroundColor: '#042d1f',
        borderRadius: 12,
        paddingHorizontal: 25,
        paddingVertical: 10,
        marginBottom: 35,
        alignItems: 'center',
    },
    insigniaDateText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'InterDisplay-SemiBold',
    },
    insigniaDescriptionText: {
        fontSize: 18,
        color: '#1A1A1A',
        textAlign: 'center',
        lineHeight: 26,
        fontFamily: 'InterDisplay-Regular',
    },
    insigniaBoldText: {
        fontWeight: 'bold',
        fontFamily: 'InterDisplay-SemiBold',
    },
});
